### ISSUE TITLE
[Bug]: 胡桃工具箱更新失败，出现内部错误或内存不足，显示路径是一个我不存在的硬盘路径（我根本没有 J 盘）

### ISSUE THREAD

**Issue by xinyi1483** [DGP-Studio/Snap.Hutao.Deployment#10]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道文档站的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

win10 22H2 19045.3570

### Snap Hutao 版本

更新1.10.3版本失败

### 问题分类

安装和环境

### 发生了什么？

1、几个月前我安装了胡桃工具箱1.10.0版本（或者1.10.1记不清了），然后在前几天打开胡桃工具箱的时候弹窗提示我更新到最新的1.10.2版本，我点击了下载并安装，但是没有安装成功。
2、今天我打开胡桃箱再次弹窗安装到1.10.3版本，我再次同意更新，还是不成功。
3、于是我访问了胡桃工具箱官网下载了 Snap.Hutao.Deployment 安装器进行更新，提示我【Windows 无法注册程序包，因为出现内部错误或内存不足】，但是程序路径是一个我不存在的文件夹【D盘，硬盘存在，但是D盘没有该文件夹，隐藏文件夹也没有】
4、我于是卸载了胡桃工具箱，重新安装，还是不成功
5、再次删除 \AppData\Local\Packages 文件夹内的 60568DGPStudio.SnapHutao_wbnnev551gwxy 文件夹
6、再次尝试运行 Snap.Hutao.Deployment 安装器，这次爆出的一场是一个我不存在的硬盘，J盘
报错内容如下：
System.Runtime.InteropServices.COMException (0x80073CF6): 无法注册包。
错误 0x80070005: Windows 无法注册程序包，因为出现内部错误或内存不足
![20240610203441 987](https://github.com/DGP-Studio/Snap.Hutao/assets/123640338/0c39cf4c-7f96-4dd5-9d91-ce5f09b7bec9)

### 你期望发生的行为？

安装最新版胡桃工具箱，最好能保留原本的数据（我备份了 Userdata.db文件），保留不了也行

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by qhy040404** [comment]
你内存多大，c盘剩多少

**Comment by xinyi1483** [comment]
> 你内存多大，c盘剩多少

内存32G，C盘256G，156G可用

**Comment by xinyi1483** [comment]
> > 你内存多大，c盘剩多少
> 
> 内存32G，C盘256G，156G可用，D盘675G，613G可用，E盘1T，578G可用，F盘1T，881G可用，G盘4T，1.44T可用，F盘和G盘是机械盘

**Comment by xinyi1483** [comment]
> > > 你内存多大，c盘剩多少
> > 
> > 
> > 内存32G，C盘256G，156G可用，D盘675G，613G可用，E盘1T，578G可用，F盘1T，881G可用，G盘4T，1.44T可用，F盘和G盘是机械盘

![image](https://github.com/DGP-Studio/Snap.Hutao.Deployment/assets/123640338/8e7b3560-3210-44b3-bb0b-384fccc0f30e)

**Comment by qhy040404** [comment]
你改过默认安装位置吗

**Comment by Mikachu2333** [comment]
提问

1. 现在能否卸载胡桃？（卸载胡桃不会移除你的用户数据），如果可以，请尝试卸载胡桃后检查WindowsApps 目录下是否还有名称中含有“hutao”的文件夹，如果有，请使用安全软件的粉碎工具删除后，再尝试重新安装
（旧版胡桃与新版胡桃签名不一致可导致更新失败）
2. 之前是否更改过 WindowsApps 目录的权限？（没听说过或没有印象先默认没有），如果有，我建议您重装电脑系统，因为该目录为电脑重要目录，更改权限不仅会导致胡桃出现问题，还会使许多msix类的程序故障

**Comment by Mikachu2333** [comment]
https://github.com/DGP-Studio/Snap.Hutao/issues/1211

该问题已被解决，请参考此解决方案

**Comment by Mikachu2333** [comment]
此外，下次请把错误代码放在开头，便于定位问题

**Comment by xinyi1483** [comment]
> 你改过默认安装位置吗

胡桃工具箱里面有一个设置路径的，忘了是数据保存路径还是其他什么，修改过，安装位置是Snap.Hutao.Deployment 安装器自动在安装器所在的位置安装的

**Comment by xinyi1483** [comment]
> 提问
> 
> 1. 现在能否卸载胡桃？（卸载胡桃不会移除你的用户数据），如果可以，请尝试卸载胡桃后检查WindowsApps 目录下是否还有名称中含有“hutao”的文件夹，如果有，请使用安全软件的粉碎工具删除后，再尝试重新安装
>    （旧版胡桃与新版胡桃签名不一致可导致更新失败）
> 2. 之前是否更改过 WindowsApps 目录的权限？（没听说过或没有印象先默认没有），如果有，我建议您重装电脑系统，因为该目录为电脑重要目录，更改权限不仅会导致胡桃出现问题，还会使许多msix类的程序故障

1、比较习惯用Geek卸载软件，但是胡桃工具箱并没有在geek中显示，所以直接删除了安装位置（E:\Games\mihoyo\hutao）的文件夹，并且再次删除%userprofile%/Documents/Hutao文件夹和C:\Users\xinyi\AppData\Local\Packages文件夹
2、没有修改过C:\Program Files\WindowsApps的权限，C:\Users\xinyi\AppData\Local\Packages文件夹因为第一次次安装胡桃工具的时候修改过权限，

**Comment by qhy040404** [comment]
> 但是胡桃工具箱并没有在geek中显示

首先，胡桃是msix包，要用geek卸先点查看切换到ms store app
![image](https://github.com/DGP-Studio/Snap.Hutao.Deployment/assets/45379733/f3f6f8c6-3a4b-4afc-b4ef-4acb83728dc4)

> 安装位置（E:\Games\mihoyo\hutao）

你删的只是安装包，要卸载去系统设置

> C:\Users\xinyi\AppData\Local\Packages 修改过权限

卸完重装先试试，如果还是不行可以参考 DGP-Studio/Snap.Hutao#1211 试试

**Comment by xinyi1483** [comment]
> > 但是胡桃工具箱并没有在geek中显示
> 
> 首先，胡桃是msix包，要用geek卸先点查看切换到ms store app ![image](https://private-user-images.githubusercontent.com/45379733/338555746-f3f6f8c6-3a4b-4afc-b4ef-4acb83728dc4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxMDgyNDQsIm5iZiI6MTcxODEwNzk0NCwicGF0aCI6Ii80NTM3OTczMy8zMzg1NTU3NDYtZjNmNmY4YzYtM2E0Yi00YWZjLWI0ZWYtNGFjYjgzNzI4ZGM0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjExVDEyMTIyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVkNDIyNmQyMDZhZjQ4ZTdhZTBlMzNjNjBhMjgyZmFiM2M4ZTUwMjQ5MzRiNWEwZWYyOThlNDJlYmFhMmIzYmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.crghdO-evCmlzH9CvZR9fR8faPeM5kSR2NHkjGwwL1g)
> 
> > 安装位置（E:\Games\mihoyo\hutao）
> 
> 你删的只是安装包，要卸载去系统设置
> 
> > C:\Users\xinyi\AppData\Local\Packages 修改过权限
> 
> 卸完重装先试试，如果还是不行可以参考 [DGP-Studio/Snap.Hutao#1211](https://github.com/DGP-Studio/Snap.Hutao/issues/1211) 试试

现在胡桃工具箱在开始菜单和Geek中都找不到了，安装不成功，我想彻底删除的话需要删除哪些地方

**Comment by Lightczx** [comment]
没救了，remake吧
