### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by qimingnan17** [DGP-Studio/Snap.Hutao.Deployment#15]
大大可以辛苦一下做一个手机端吗然后理由网盘数据互通例如坚果云

**Comment by Lightczx** [comment]
不能，而且你issue发错仓库了

**Comment by qimingnan17** [comment]
哦哦那我就不重新发了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年9月18日(周三) 上午8:59
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [DGP-Studio/Snap.Hutao.Deployment] 建议 (Issue #15)




 
不能，而且你issue发错仓库了
