### ISSUE TITLE
安裝程式視窗部分文字未正確顯示

### ISSUE THREAD

**Issue by SSB-ARFCN** [DGP-Studio/Snap.Hutao.Deployment#7]
![image](https://github.com/DGP-Studio/Snap.Hutao.Deployment/assets/107019852/b98ac721-4106-4060-a8d2-c86bd08ea053)
Snap.Hutao.Deployment.exe

""?始下?包文件...""
""?法找到所需?? [GlobalSign Code Signing Root R45]，正在? GlobalSign 下?""
""正在向 本地?算机/受信任的根????机构 添加??
如果你?法理解?窗中的文本，??? [是] ""
""?于更多安全信息，?查看下方的网址""

windows10 64bit 22H2 19045.3803
繁體中文

**Comment by Lightczx** [comment]
不支持繁体中文，英文凑合看
